name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Models
  json_annotation: ^4.9.0

  freezed_annotation: ^3.0.0
  # Navigation

  auto_route: ^10.1.0+1
  # Debugging
  river_delta:
    path: ../

  # Networking
  retrofit: ^4.4.2
  mockzilla: ^1.0.1
  dio: ^5.8.0+1

  # Logging
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  freezed: ^3.0.6
  auto_route_generator: ^10.2.3
  json_serializable: ^6.9.0

  # Linting
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.3
  riverpod_lint: ^2.3.10
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true