name: river_delta
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  devtools_app_shared: ^0.2.2
  json_annotation: ^4.9.0
  collection: ^1.18.0
  mockito: ^5.4.4
  vm_service: ^14.2.5
  test:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true