name: pull-request

on:
  pull-request:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Fastlane
        run: sudo gem install fastlane
      - name: Execute Fastlane scripts
        run: fastlane pull-request
